[versions]
activityCompose = "1.9.0"
androidGradlePlugin = "8.4.2"
appcompat = "1.7.0"
bugsnagAndroid = "6.6.1"
bugsnagAndroidGradlePlugin = "8.1.0"
bugsnagAndroidPerformance = "1.4.0"
composeBom = "2024.02.00-alpha02"
composeCompiler = "1.5.14"
constraintlayout = "2.1.4"
hiddenapibypass = "4.3"
kotlin = "2.0.0"
kotlinxCoroutinesCore = "1.9.0-RC"
markwon = "2.0.2"
material = "1.12.0"
preferenceKtx = "1.2.1"
seekbarpreference = "46a6643c79"
taskerpluginlibrary = "0.4.10"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
bugsnag-android-performance = { module = "com.bugsnag:bugsnag-android-performance", version.ref = "bugsnagAndroidPerformance" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "composeBom" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
markwon = { module = "ru.noties:markwon", version.ref = "markwon" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
seekBarPreference = { module = "com.github.zacharee:SeekBarPreference", version.ref = "seekbarpreference" }
taskerpluginlibrary = { module = "com.joaomgcd:taskerpluginlibrary", version.ref = "taskerpluginlibrary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
bugsnag-android = { id = "com.bugsnag.android.gradle", version.ref = "bugsnagAndroidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
